CREATE VIEW VehicleTI AS
SELECT *  FROM VEHICLES
WHERE FLOOR(DATEDIFF(day, VEHICLES.Release_D , getDate()) / 365.25) > 4 
and FLOOR(DATEDIFF(day, VEHICLES.Release_D , getDate()) / 365.25) < 10
and FLOOR(DATEDIFF(day, VEHICLES.TID , getDate()) / 365.25) > 2
UNION
SELECT * FROM VEHICLES
WHERE FLOOR(DATEDIFF(day, VEHICLES.Release_D , getDate()) / 365.25) > 10 AND 
FLOOR(DATEDIFF(day, VEHICLES.TID , getDate()) / 365.25) > 1
