CREATE TABLE ACCIDENTS 
    (
     ID INTEGER IDENTITY(1,1)NOT NULL , 
     Num_of_victims INTEGER NOT NULL , 
     Amount_of_damage FLOAT , 
     Reason VARCHAR (30) , 
     Road_conditions VARCHAR (30) , 
     Area VARCHAR (30) NOT NULL , 
     Type VARCHAR (30) NOT NULL , 
     Date DATE NOT NULL 
    )
GO

ALTER TABLE ACCIDENTS ADD CONSTRAINT ACCIDENTS_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE HISTORYS 
    (
     ACCIDENTS_ID INTEGER NOT NULL , 
     VEHICLES_ID INTEGER NOT NULL 
    )
GO

ALTER TABLE HISTORYS ADD CONSTRAINT HISTORYS_PK PRIMARY KEY CLUSTERED (ACCIDENTS_ID, VEHICLES_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE OWNERS 
    (
     ID INTEGER IDENTITY(1,1)NOT NULL , 
     Surname VARCHAR (30) NOT NULL , 
     Name VARCHAR (30) NOT NULL , 
     Middle_name VARCHAR (30) NOT NULL , 
     Address VARCHAR (60) NOT NULL , 
     Birth_D DATE NOT NULL 
    )
GO

ALTER TABLE OWNERS ADD CONSTRAINT OWNERS_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE USERS 
    (
     ID INTEGER IDENTITY(1,1)NOT NULL , 
     Login VARCHAR (20) NOT NULL , 
     Password VARCHAR (20) NOT NULL 
    )
GO

ALTER TABLE USERS ADD CONSTRAINT USERS_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE VEHICLES 
    (
     ID INTEGER IDENTITY(1,1)NOT NULL , 
     Number VARCHAR (9) NOT NULL , 
     VIN CHAR (17) NOT NULL , 
     Brand VARCHAR (30) NOT NULL , 
     Release_D DATE NOT NULL , 
     Engine_volume VARCHAR (30) NOT NULL , 
     Engine_n VARCHAR (30) NOT NULL , 
     Chasis_n VARCHAR (30) NOT NULL , 
     Body_n VARCHAR (30) NOT NULL , 
     Color VARCHAR (30) NOT NULL , 
     Type VARCHAR (30) NOT NULL , 
	 Wanted BIT,
     OWNERS_ID INTEGER , 
     TID DATE 
    )
GO

ALTER TABLE VEHICLES ADD CONSTRAINT VEHICLES_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE HISTORYS 
    ADD CONSTRAINT HISTORYS_ACCIDENTS_FK FOREIGN KEY 
    ( 
     ACCIDENTS_ID
    ) 
    REFERENCES ACCIDENTS 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE HISTORYS 
    ADD CONSTRAINT HISTORYS_VEHICLES_FK FOREIGN KEY 
    ( 
     VEHICLES_ID
    ) 
    REFERENCES VEHICLES 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE VEHICLES 
    ADD CONSTRAINT VEHICLES_OWNERS_FK FOREIGN KEY 
    ( 
     OWNERS_ID
    ) 
    REFERENCES OWNERS 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

insert into USERS(login, password)values('Admin','Admin')